<?php

namespace App\Core\Provider\Payment;

use App\Core\DTO\PaymentSessionDTO;
use Symfony\Component\HttpFoundation\Request;

interface PaymentProviderInterface
{
    public const PAID_STATUS = 'paid';

    public function createSession(
        float $amount,
        string $currency,
        string $successUrl,
        string $cancelUrl,
    ): ?PaymentSessionDTO;

    public function retrieveSession(string $sessionId): ?PaymentSessionDTO;

    public function getIdentifier(): string;

    public function getDisplayName(): string;

    public function getIcon(): string;

    public function isConfigured(): bool;

    public function getDescription(): string;

    public function getSupportedCurrencies(): array;

    public function getMetadata(): array;

    /**
     * Get the route name for successful payment callback.
     *
     * @return string Route name (e.g., 'payment_callback_success')
     */
    public function getSuccessCallbackRoute(): string;

    /**
     * Get the route name for canceled payment callback.
     *
     * @return string Route name (e.g., 'payment_callback_cancel')
     */
    public function getCancelCallbackRoute(): string;

    /**
     * Extract session ID from callback request.
     * Different providers use different query parameters (Stripe: session_id, PayPal: token).
     *
     * @param Request $request The callback request
     * @return string|null The session ID or null if not found
     */
    public function extractSessionIdFromCallback(Request $request): ?string;

    /**
     * Build the complete success URL with provider-specific parameters.
     * Providers can add their required query parameters or placeholders to the base URL.
     *
     * @param string $baseUrl The base callback URL generated by the router
     * @return string The complete URL with provider-specific parameters
     */
    public function buildSuccessUrl(string $baseUrl): string;

    /**
     * Build the complete cancel URL with provider-specific parameters.
     *
     * @param string $baseUrl The base callback URL generated by the router
     * @return string The complete URL with provider-specific parameters
     */
    public function buildCancelUrl(string $baseUrl): string;
}